# Copyright (C) 2021 Ben Elliston
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

"""Backend routines for the EnergyPlus (EPW) file format."""

import datetime


def preamble(filehandle, args, station):
    """Emit the required headers for an EPW file."""
    print(f'LOCATION,{station.name} in {args.year},{station.state},'
          f'AUS,BoM,{station.number},{station.location.lat:.2f},'
          f'{station.location.lon:.2f},{args.tz:.1f},{station.altitude:.1f}',
          file=filehandle)

    print('DESIGN CONDITIONS,0', file=filehandle)
    print('TYPICAL/EXTREME PERIODS,,', file=filehandle)
    print('GROUND TEMPERATURES,,,,,,', file=filehandle)
    print('HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0', file=filehandle)
    print('COMMENTS 1,Generated by weather-maker.py from Bureau of '
          f'Meteorology solar and weather data ({args.year})',
          file=filehandle)
    print('COMMENTS 2,Please report weather-maker bugs to bje@air.net.au',
          file=filehandle)
    print('DATA PERIODS,1,1,Data,Sunday,1/ 1,12/31', file=filehandle)


def record(filehandle, args, rec):
    """Emit a record in EPW format."""
    time = datetime.datetime(args.year, 1, 1)
    time += datetime.timedelta(hours=rec['hour'])
    if time.month == 2 and time.day == 29:
        # Skip leap day
        return

    text = f"{time.year},{time.month},{time.day},{time.hour + 1},50," \
        f"{' ' * 39},{rec['dry-bulb']:.1f},{rec['dew-point']:.1f}," \
        f"{rec['rel-humidity']},{rec['atm-pressure']},9999,9999,9999," \
        f"{rec['ghi']},{rec['dni']},{rec['dhi']},999999,999999,999999," \
        f"999999,{rec['wind-direction']},{rec['wind-speed']:.1f},99,99," \
        f"9999,99999,9,999999999,99999,0.999,999,99,999,0,99"
    print(text, file=filehandle)
