# Copyright (C) 2021 Ben Elliston
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

"""Backend routines for the EnergyPlus (EPW) file format."""

import datetime


def preamble(filehandle, station, args):
    """Emit the required headers for an EPW file."""
    print('LOCATION,%s in %s,%s,AUS,BoM,%s,%.2f,%.2f,%.1f,%.1f' %
          (station.name, args.year, station.state, station.number,
           station.location.lat, station.location.lon,
           args.tz, station.altitude), file=filehandle)

    print('DESIGN CONDITIONS,0', file=filehandle)
    print('TYPICAL/EXTREME PERIODS,,', file=filehandle)
    print('GROUND TEMPERATURES,,,,,,', file=filehandle)
    print('HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0', file=filehandle)
    print('COMMENTS 1,Generated by weather-maker.py from Bureau of '
          'Meteorology solar and weather data (%d)' % args.year,
          file=filehandle)
    print('COMMENTS 2,Please report weather-maker bugs to bje@air.net.au',
          file=filehandle)
    print('DATA PERIODS,1,1,Data,Sunday,1/ 1,12/31', file=filehandle)


def record(filehandle, args, rec):
    """Emit a record in EPW format."""
    time = datetime.datetime(args.year, 1, 1)
    time += datetime.timedelta(hours=rec['hour'])
    if time.month == 2 and time.day == 29:
        # Skip leap day
        return

    text = '%d,%d,%d,%d,50,%s,%.1f,%.1f,%d,%d,9999,9999,9999,%d,%d,%d,' \
        '999999,999999,999999,999999,%d,%.1f,99,99,9999,99999,9,999999999,' \
        '99999,0.999,999,99,999,0,99' \
        % (time.year, time.month, time.day, time.hour + 1, '_' * 39,  # noqa: E501
           rec['dry-bulb'],
           rec['dew-point'], rec['rel-humidity'], rec['atm-pressure'],
           rec['ghi'], rec['dni'], rec['dhi'], rec['wind-direction'],
           rec['wind-speed'])
    print(text, file=filehandle)
